# Site settings
title: Goose Haus
email: angus@goose.haus
description: > # this means to ignore newlines until "baseurl:"
  Adventures in programming, math, books, and bikes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://goose.haus" # the base hostname & protocol for your site
twitter_username: angusiguess
github_username:  angusiguess

# Build settings
markdown: kramdown
